# TODO: https://www.authelia.com/configuration/security/access-control/
access_control:
  default_policy: deny
  rules:
    - domain:
        - castelnuovo.xyz
        - authelia.castelnuovo.xyz
        - s3.castelnuovo.xyz
        - s3-console.castelnuovo.xyz
      policy: bypass

    - domain: email.castelnuovo.xyz
      policy: bypass
      resources:
        - "^/api/v1([/?].*)?$"
        - "^/.well-known([/?].*)?$"

    - domain: stats.castelnuovo.xyz
      policy: bypass
      resources:
        - "^/api([/?].*)?$"
        - "^/js([/?].*)?$"
        - "^/css([/?].*)?$"
        - "^/images([/?].*)?$"
        - "^/share([/?].*)?$"

    - domain:
        - proxmox.castelnuovo.xyz
        - ldap.castelnuovo.xyz
        - portainer.castelnuovo.xyz
        - traefik.castelnuovo.xyz
      policy: two_factor

    - domain: "*.castelnuovo.xyz"
      # subject:
      # - "group:admins"
      policy: one_factor

theme: dark
default_redirection_url: https://authelia.castelnuovo.xyz

log:
  level: info
  file_path: /config/authelia.log
  keep_stdout: true

totp:
  disable: false
  issuer: authelia.castelnuovo.xyz

webauthn:
  disable: true
  display_name: authelia.castelnuovo.xyz

authentication_backend:
  password_reset:
    disable: true
    custom_url: ""
  refresh_interval: 1m
  ldap:
    implementation: custom
    url: ldap://ldap:389
    timeout: 5s
    start_tls: false
    #tls:
    #  skip_verify: false
    #  minimum_version: TLS1.2
    base_dn: dc=castelnuovo,dc=xyz
    username_attribute: uid
    additional_users_dn: ou=people
    users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    user: uid=admin,ou=people,dc=castelnuovo,dc=xyz

session:
  name: authelia_session
  domain: castelnuovo.xyz
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

regulation:
  max_retries: 10
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notification.txt
  # smtp:
  #   host: email.local.castelnuovo.xyz
  #   port: 25
  #   username: luca
  #   sender: "authelia@email.castelnuovo.xyz"
  #   subject: "[authelia.castelnuovo.xyz] {title}"
  #   disable_require_tls: true
