# TODO: https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:
    - domain: authelia.castelnuovo.xyz
      policy: bypass

    - domain: castelnuovo.xyz
      policy: bypass

    - domain: email.castelnuovo.xyz
      policy: bypass
      resources:
        - "^/v1([/?].*)?$"
        - "^/.well-known([/?].*)?$"

    - domain: media.castelnuovo.xyz
      policy: bypass

    - domain: "*.castelnuovo.xyz"
      # subject:
      # - "group:admins"
      policy: two_factor

theme: dark
default_redirection_url: https://authelia.castelnuovo.xyz

log:
  level: info
  file_path: /config/authelia.log
  keep_stdout: true

totp:
  disable: false
  issuer: authelia.castelnuovo.xyz

webauthn:
  disable: true
  display_name: authelia.castelnuovo.xyz

authentication_backend:
  password_reset:
    disable: false
    custom_url: "https://ldap.castelnuovo.xyz/reset-password/step1"
  refresh_interval: 1m
  ldap:
    implementation: custom
    url: ldap://ldap:389
    timeout: 5s
    start_tls: false
    #tls:
    #  skip_verify: false
    #  minimum_version: TLS1.2
    base_dn: dc=castelnuovo,dc=xyz
    username_attribute: uid
    additional_users_dn: ou=people
    # To allow sign in both with username and email, one can use a filter like
    # (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
    users_filter: (&({username_attribute}={input})(objectClass=person))
    additional_groups_dn: ou=groups
    groups_filter: (member={dn})
    group_name_attribute: cn
    mail_attribute: mail
    display_name_attribute: displayName
    user: uid=admin,ou=people,dc=castelnuovo,dc=xyz
  # file:
  #   path: /config/users_database.yml
  #   password:
  #     memory: 1024
  #     parallelism: 8

session:
  name: authelia_session
  domain: castelnuovo.xyz
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

regulation:
  max_retries: 10
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: true
  smtp:
    host: ip.castelnuovo.xyz
    port: 587
    username: luca
    sender: "authelia.castelnuovo.xyz <auth@castelnuovo.xyz>"
    subject: "[authelia.castelnuovo.xyz] {title}"
