# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:

    - domain:
        - "authelia.castelnuovo.xyz"
      policy: bypass

    - domain: "*.castelnuovo.xyz"
      # subject:
        # - "group:admins"
      policy: two_factor

theme: dark
# jwt_secret: "2pdBxDeYXgbtDmIwhhvlDejNtZrdW8Z25ke4qaYQQDQ06Yudna7i4R4JbXTRZtVh"
default_redirection_url: https://castelnuovo.xyz

log:
  level: info
  file_path: /config/authelia.log
  keep_stdout: true

totp:
  disable: false
  issuer: authelia.castelnuovo.xyz

webauthn:
  disable: true
  display_name: authelia.castelnuovo.xyz

authentication_backend:
  disable_reset_password: true
  file:
    path: /config/users_database.yml
    password:
      memory: 1024
      parallelism: 8

session:
  name: authelia_session
  domain: castelnuovo.xyz
  same_site: lax
  # secret: "2pdBxDeYXgbtDmIwhhvlDejNtZrdW8Z25ke4qaYQQDQ06Yudna7i4R4JbXTRZtVh" # TODO: move to a file
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

regulation:
  max_retries: 10
  find_time: 10m
  ban_time: 12h

storage:
  # encryption_key: "2pdBxDeYXgbtDmIwhhvlDejNtZrdW8Z25ke4qaYQQDQ06Yudna7i4R4JbXTRZtVh" # TODO: move to a file
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt

  # smtp: # TODO:
  #   host: smtp.mailbox.org
  #   port: 465
  #   username: luca@castelnuovo.xyz
    # password: YOUR_EMAIL_PASSWORD
    # sender: "authelia.castelnuovo.xyz <luca@castelnuovo.xyz>" # test with authelia.castelnuovo.xyz
  #   subject: "[authelia.castelnuovo.xyz] {title}"
    # startup_check_address: test@authelia.com
