# TODO: https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:

    - domain: authelia.castelnuovo.xyz
      policy: bypass

    - domain: email.castelnuovo.xyz
      policy: bypass
      resources:
        - "^/v1([/?].*)?$"

    - domain: "*.castelnuovo.xyz"
      # subject:
        # - "group:admins"
      policy: two_factor

theme: dark
default_redirection_url: https://authelia.castelnuovo.xyz

log:
  level: info
  file_path: /config/authelia.log
  keep_stdout: true

totp:
  disable: false
  issuer: authelia.castelnuovo.xyz

webauthn:
  disable: true
  display_name: authelia.castelnuovo.xyz

authentication_backend:
  disable_reset_password: false
  file:
    path: /config/users_database.yml
    password:
      memory: 1024
      parallelism: 8

session:
  name: authelia_session
  domain: castelnuovo.xyz
  same_site: lax
  expiration: 1h
  inactivity: 5m
  remember_me_duration: 1M

regulation:
  max_retries: 10
  find_time: 10m
  ban_time: 12h

storage:
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: false
  smtp:
    host: ip.castelnuovo.xyz
    port: 587
    username: luca
    sender: "authelia.castelnuovo.xyz <auth@castelnuovo.xyz>"
    subject: "[authelia.castelnuovo.xyz] {title}"
    startup_check_address: test@authelia.com
