version: "3"

services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    volumes:
      - .:/config
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.entryPoints: https
    # environment: # TODO: https://www.authelia.com/docs/configuration/secrets.html
      # - AUTHELIA_JWT_SECRET_FILE=/config/secrets/jwt
      # - AUTHELIA_SESSION_SECRET_FILE=/config/secrets/session
      # - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/config/secrets/smtp
      # - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/config/secrets/encryption

networks:
  traefik-proxy:
    driver: bridge
    external: true
