version: "3"

services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    volumes:
      - .:/config
    labels:
      traefik.enable: true
      traefik.http.routers.authelia.entryPoints: https
    environment:
      AUTHELIA_JWT_SECRET: "2pdBxDeYXgbtDmIwhhvlDejNtZrdW8Z25ke4qaYQQDQ06Yudna7i4R4JbXTRZtVh"
      AUTHELIA_SESSION_SECRET: "2pdBxDeYXgbtDmIwhhvlDejNtZrdW8Z25ke4qaYQQDQ06Yudna7i4R4JbXTRZtVh"
      AUTHELIA_STORAGE_ENCRYPTION_KEY: "2pdBxDeYXgbtDmIwhhvlDejNtZrdW8Z25ke4qaYQQDQ06Yudna7i4R4JbXTRZtVh"
      # AUTHELIA_NOTIFIER_SMTP_PASSWORD: "/config/secrets/smtp"

networks:
  traefik-proxy:
    driver: bridge
    external: true
