version: v2

teleport:
  nodename: teleport.castelnuovo.xyz
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  public_addr: teleport.castlenuovo.xyz:3025

ssh_service:
  enabled: "yes"
  # labels:
  # env: example
  commands:
    - name: hostname
      command: [hostname]
      period: 1m0s

proxy_service:
  enabled: "yes"
  acme: {}
  https_keypairs: []
  public_addr: teleport.castelnuovo.xyz:443
  tunnel_public_addr: teleport.castelnuovo.xyz:443
  # ssh_public_addr: teleport.castelnuovo.xyz:3023

app_service:
  enabled: "no"

kubernetes_service:
  enabled: "no"

windows_desktop_service:
  enabled: "no"
