version: v1
# version: v2

teleport:
  nodename: teleport.castelnuovo.xyz
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""

auth_service:
  enabled: "yes"
  cluster_name: teleport.castelnuovo.xyz
  public_addr: teleport.castlenuovo.xyz:3025
  proxy_listener_mode: separate
  # proxy_listener_mode: multiplex

ssh_service:
  enabled: "yes"
  commands:
    - name: hostname
      command: [hostname]
      period: 1m0s

proxy_service:
  enabled: "yes"
  acme: {}
  https_keypairs: []
  public_addr: teleport.castelnuovo.xyz:443
