version: v2

teleport:
  nodename: teleport.castelnuovo.xyz
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  cluster_name: teleport.castelnuovo.xyz
  public_addr: teleport.castlenuovo.xyz:3025
  # proxy_listener_mode: multiplex

ssh_service:
  enabled: "yes"
  commands:
    - name: hostname
      command: [hostname]
      period: 1m0s
  # enhanced_recording:
    # enabled: true

proxy_service:
  enabled: "yes"
  https_keypairs: []
  acme: {}
  public_addr: teleport.castelnuovo.xyz:443
