#
# A Sample Teleport configuration file.
#
# Things to update:
#  1. license.pem: You only need a license from https://dashboard.goteleport.com
#     if you are an Enterprise customer.
#
version: v2

teleport:
  nodename: teleport.castelnuovo.xyz
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""

auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  public_addr: auth.example.com:3025

ssh_service:
  enabled: "yes"
  # labels:
  # env: example
  commands:
    - name: hostname
      command: [hostname]
      period: 1m0s

proxy_service:
  enabled: "yes"
  # public_addr: teleport.castelnuovo.xyz:443
  # ssh_public_addr: teleport.castelnuovo.xyz:3023
  https_keypairs:
  - key_file: /var/lib/teleport/webproxy_key.pem
    cert_file: /var/lib/teleport/webproxy_cert.pem
  acme: {}

app_service:
  enabled: "no"

kubernetes_service:
  enabled: "no"

windows_desktop_service:
  enabled: "no"
