version: "3"

services:
  email:
    image: andris9/emailengine:latest
    container_name: email
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
      - email-redis-bridge
    labels:
      traefik.enable: true
      traefik.http.routers.email.entryPoints: https
      traefik.http.services.email.loadbalancer.server.port: 3000
    environment:
      EENGINE_SECRET: ${EENGINE_SECRET:?error}
      EENGINE_REDIS: "redis://email-redis:6379/2"
      EENGINE_SETTINGS: >
        {
            "smtpServerEnabled": true,
            "smtpServerPort": 587,
            "smtpServerHost": "0.0.0.0",
            "smtpServerAuthEnabled": true,
            "smtpServerPassword": ""
        }
    depends_on:
      - email-redis
    ports:
      - 587:587

  email-redis:
    image: redis:latest
    container_name: email-redis
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - email-redis-bridge
    volumes:
      - ./redis:/data
    expose:
      - 6379

networks:
  traefik-proxy:
    driver: bridge
    external: true
  email-redis-bridge:
    driver: bridge
