version: "3"

services:
  email:
    image: andris9/emailengine:latest
    container_name: email
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    labels:
      traefik.enable: true
      traefik.http.routers.email.entryPoints: https
      traefik.http.services.email.loadbalancer.server.port: 3000
    environment:
      EENGINE_SECRET: ${EENGINE_SECRET:?error}
      EENGINE_REDIS: 'redis://redis:6379/emailengine'

networks:
  traefik-proxy:
    driver: bridge
    external: true
