api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      middlewares:
        - https-redirect@file

  websecure:
    address: :443
    http:
      middlewares:
        - default-headers@file
      tls:
        certResolver: letsencrypt

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: luca@castelnuovo.xyz
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
