version: "3"

services:
  storage:
    image: minio/minio:latest
    container_name: storage
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    labels:
      traefik.enable: true
      traefik.http.routers.storage.entryPoints: https
      traefik.http.services.storage.loadbalancer.server.port: 9000

      traefik.http.routers.storage-console.entryPoints: https
      traefik.http.services.storage-console.loadbalancer.server.port: 9001
      traefik.http.routers.storage-console.rule: Host(`storage-console.castelnuovo.xyz`)
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?error}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?error}
    command: server --console-address ":9001" /data

networks:
  traefik-proxy:
    driver: bridge
    external: true
