version: "3"

services:
  s3:
    image: minio/minio
    container_name: s3
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    labels:
      traefik.enable: true

      traefik.http.routers.s3.rule: Host(`s3.castelnuovo.xyz`)
      traefik.http.routers.s3.service: s3
      traefik.http.services.s3.loadbalancer.server.port: 9004

      traefik.http.routers.s3-console.rule: Host(`s3-console.castelnuovo.xyz`)
      traefik.http.routers.s3-console.service: s3-console
      traefik.http.services.s3-console.loadbalancer.server.port: 9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?error}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?error}
      MINIO_SERVER_URL: https://s3.castelnuovo.xyz
      MINIO_BROWSER_REDIRECT_URL: https://s3-console.castelnuovo.xyz
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001" --address ":9004"
    ports:
      - 9001:9001
      - 9004:9004

networks:
  traefik-proxy:
    driver: bridge
    external: true
