version: "3"

services:
  storage:
    image: minio/minio:latest
    container_name: storage
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    labels:
      traefik.enable: true

      traefik.http.routers.storage.rule: Host(`storage.castelnuovo.xyz`)
      traefik.http.routers.storage.entrypoints: https
      traefik.http.routers.storage.service: svc_storage
      traefik.http.services.svc_storage.loadbalancer.server.port: 9000

      traefik.http.routers.storage-console.rule: Host(`storage-console.castelnuovo.xyz`)
      traefik.http.routers.storage-console.entrypoints: https
      traefik.http.routers.storage-console.service: svc_storage-console
      traefik.http.services.svc_storage-console.loadbalancer.server.port: 9001
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?error}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:?error}
    command: server --console-address ":9001" /data

networks:
  traefik-proxy:
    driver: bridge
    external: true
