version: "3"

services:
  mariadb:
    image: linuxserver/mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      TZ: Europe/Amsterdam
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?error}
      MYSQL_USER: ${MYSQL_USER:?error}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?error}
    volumes:
      - ./mariadb:/config
    ports:
      - 3306:3306/tcp
