version: "3"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - traefik-proxy
    volumes:
      - ./data:/data

networks:
  traefik-proxy:
    driver: bridge
    external: true
